<?php
/**
 * Class Rest_API\V4\Label\Service file.
 *
 * @package PostNLWooCommerce\Rest_API\V4\Label
 */

namespace PostNLWooCommerce\Rest_API\V4\Label;

use Postnl\Sdk\Client\PostnlClientInterface;
use Postnl\Sdk\RequestData\V4\ShipmentDelivery\ShipmentDeliveryRequest;
use Postnl\Sdk\Service\ShipmentDelivery\V4\Response\LabelConfirmResponseInterface;
use PostNLWooCommerce\Order\Base as Order_Base;
use PostNLWooCommerce\Rest_API\Contracts\Label_Service_Interface;
use PostNLWooCommerce\Rest_API\SDK\Client_Factory;
use PostNLWooCommerce\Rest_API\SDK\Exception_Converter;
use PostNLWooCommerce\Rest_API\Shipping;
use PostNLWooCommerce\Utils;
use Psr\Log\LoggerInterface;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Class Service
 *
 * V4 SDK implementation of the outbound shipping-label flow. It confirms a
 * label through the /shipment/delivery/v4/labelconfirm endpoint and stores the
 * result in the same _postnl_order_metadata['labels'] shape as the legacy path,
 * tagged api_version = v4.
 *
 * Scope is intentionally tight: only a happy-path single domestic NL parcel
 * (single collo, base product 3085, no extra services, no return, no pickup or
 * delivery-day selection) is routed to V4. Everything else — services,
 * international, multi-collo, pickup, delivery-day — falls back to the untouched
 * legacy pipeline so behaviour is unchanged until those flows are migrated
 * (tasks 19–21). Because both gates (a validated V4 key and the per-flow flag)
 * default off, merging this changes nothing for merchants.
 *
 * Barcode note: the barcode is generated by the (still-legacy) barcode flow in
 * Order\Base::save_meta_value() and supplied on the request so the persisted
 * barcodes[] and the label's barcode stay in sync. The barcode returned by
 * labelconfirm is captured and used for the label record. When the barcode flow
 * itself migrates (task 14) the pre-issue step can be dropped and the
 * auto-issued barcode used directly.
 *
 * Extends Order\Base to reuse put/merge helpers and the legacy pipeline for the
 * fallback, mirroring Legacy\Label_Service.
 *
 * The PSR-3 logger is required, not optional, exactly as in V4\Timeframe\Service
 * and V4\Pickup_Location\Service: it is where a failed label call's real cause
 * survives (Exception_Converter hands the merchant a safe message and keeps the
 * SDK's own only as the previous exception). Legacy label generation writes every
 * request and response to the WooCommerce log via Rest_API\Base::send_request(),
 * so without this the V4 path would be the only label flow that fails with no
 * trail at all. Wiring passes a Logger_Adapter, so V4 entries land in the same
 * WooCommerce log as the legacy path and honour the same "enable logging"
 * setting.
 *
 * @since   5.9.9
 * @package PostNLWooCommerce\Rest_API\V4\Label
 */
class Service extends Order_Base implements Label_Service_Interface {

	/**
	 * SDK client factory.
	 *
	 * @var Client_Factory
	 */
	private $client_factory;

	/**
	 * PostNL V4 API key used to authenticate SDK requests.
	 *
	 * @var string
	 */
	private $v4_key;

	/**
	 * PSR-3 logger the failure path reports through.
	 *
	 * @var LoggerInterface
	 */
	private $logger;

	/**
	 * Service constructor.
	 *
	 * The API key and the logger are both required rather than defaulted, matching
	 * V4\Timeframe\Service and V4\Pickup_Location\Service: the key is resolved and
	 * validated by the caller that already decides whether V4 may run at all
	 * (Service_Factory::has_v4_key()), so re-deriving it here would duplicate that
	 * decision behind a fallback that silently sends an empty key; and a defaulted
	 * NullLogger would let a caller wire the service up with logging switched off —
	 * the exact gap this parameter closes.
	 *
	 * The key is marked SensitiveParameter so PHP redacts it from stack traces,
	 * matching Client_Factory::build().
	 *
	 * @since 6.0.0 Requires the resolved API key and a PSR-3 logger.
	 *
	 * @param Client_Factory  $client_factory SDK client factory.
	 * @param string          $v4_key         PostNL V4 API key.
	 * @param LoggerInterface $logger         PSR-3 logger; wiring passes a Logger_Adapter.
	 */
	public function __construct(
		Client_Factory $client_factory,
		#[\SensitiveParameter]
		string $v4_key,
		LoggerInterface $logger
	) {
		parent::__construct();
		$this->client_factory = $client_factory;
		$this->v4_key         = $v4_key;
		$this->logger         = $logger;
	}

	/**
	 * No WP hooks are registered by this service class.
	 *
	 * Required by Order\Base but intentionally a no-op here.
	 */
	public function init_hooks() {
		// Intentionally empty — this service does not register WordPress hooks.
	}

	/**
	 * Create a shipping label and return the normalized label record.
	 *
	 * Routes the happy-path domestic parcel to the V4 SDK; anything else runs
	 * the untouched legacy pipeline.
	 *
	 * @param array $post_data Context needed to build and send the label request.
	 *
	 * @return array Normalized label record keyed by label-type string.
	 *
	 * @throws \Exception If the SDK request fails (converted to the legacy error shape).
	 */
	public function create( array $post_data ): array {
		$item_info = new Shipping\Item_Info( $post_data );
		$signals   = $this->gather_signals( $item_info, $post_data );

		if ( ! Eligibility::is_eligible( $signals ) ) {
			return $this->create_label_pipeline( $post_data );
		}

		$fields   = $this->extract_fields( $item_info, $signals['mapped'], $post_data );
		$request  = Request_Builder::build( $fields );
		$response = $this->confirm_label( $request, $fields );

		return $this->store_labels( $response, $post_data['order'], (string) $fields['barcode'] );
	}

	/**
	 * Send the labelconfirm request, converting and logging any failure.
	 *
	 * @param ShipmentDeliveryRequest $request Built labelconfirm request.
	 * @param array                   $fields  Flattened field set the request was built from.
	 *
	 * @return LabelConfirmResponseInterface
	 *
	 * @throws \Exception Converted SDK error when the request fails.
	 */
	protected function confirm_label( ShipmentDeliveryRequest $request, array $fields ): LabelConfirmResponseInterface {
		try {
			return $this->build_client()->shipmentDelivery()->labelConfirm( $request );
		} catch ( \Throwable $exception ) {
			// Exception_Converter returns a plugin-shaped \Exception; its message can
			// carry raw API text (field errors, upstream messages) — escape on output.
			$error = Exception_Converter::convert( $exception );

			// The converted message is deliberately merchant-safe, and one of its
			// variants tells the reader to check these very logs, so the original SDK
			// failure has to be written here — nothing else reads getPrevious().
			//
			// The shipment reference is the merchant's own order number: it is what
			// makes the entry traceable back to a shipment, and it is store-internal
			// rather than customer-identifying, so it is kept where the address parts
			// are not.
			$this->logger->error(
				sprintf(
					'V4 label creation failed for order "%1$s" to "%2$s": %3$s (cause: %4$s: %5$s)',
					(string) ( $fields['reference'] ?? '' ),
					$this->describe_destination( $fields ),
					$error->getMessage(),
					get_class( $exception ),
					$exception->getMessage()
				)
			);

			// phpcs:ignore WordPress.Security.EscapeOutput.ExceptionNotEscaped -- Exception_Converter returns an already-escaped, translated message.
			throw $error;
		}
	}

	/**
	 * Short, log-safe description of the destination a failed label was for.
	 *
	 * Mirrors V4\Timeframe\Service::describe_destination(): legacy
	 * Rest_API\Base::send_request() writes the entire request body — recipient name,
	 * street, house number, city, email and phone included — to the same WooCommerce
	 * log, whereas this keeps only the country and the postcode's leading area
	 * digits. An error line is written whether or not anyone is debugging, while the
	 * SDK's own request logging (which does carry the address, PII-redacted) is what
	 * a merchant turns on deliberately.
	 *
	 * @param array $fields Flattened field set.
	 *
	 * @return string e.g. 'NL 1234'; empty when the payload carried no address.
	 */
	private function describe_destination( array $fields ): string {
		$country  = (string) ( $fields['receiver']['country'] ?? '' );
		$postcode = str_replace( ' ', '', (string) ( $fields['receiver']['postcode'] ?? '' ) );

		return trim( $country . ' ' . substr( $postcode, 0, 4 ) );
	}

	/**
	 * Collect the eligibility signals for an order from the legacy parser.
	 *
	 * The selected backend features are read from the raw post data (string
	 * 'yes' values), not the parsed booleans on Item_Info, because
	 * Utils::get_selected_label_features() matches on 'yes'. Passing the real
	 * options into the mapper is what lets a service-bearing combination that
	 * keeps product 3085 (e.g. insured) resolve to a services row and be
	 * rejected below, rather than silently masquerading as the base parcel.
	 *
	 * @param Shipping\Item_Info $item_info Parsed legacy item info.
	 * @param array              $post_data Original label post data.
	 * @return array Signal set consumed by is_eligible().
	 */
	private function gather_signals( Shipping\Item_Info $item_info, array $post_data ): array {
		$backend_raw = $post_data['saved_data']['backend'] ?? array();

		$origin      = (string) ( $item_info->shipper['country'] ?? '' );
		$destination = Utils::get_shipping_zone(
			(string) ( $item_info->receiver['country'] ?? '' ),
			(string) ( $item_info->receiver['state'] ?? '' )
		);

		$has_return = ! empty( $item_info->shipment['return_barcode'] )
			|| ! empty( $item_info->shipment['shipping_return_barcode'] )
			|| ! empty( $item_info->shipment['return_options'] )
			|| 'yes' === ( $backend_raw['create_return_label'] ?? '' )
			|| 'yes' === ( $backend_raw['create_shipment_return_label'] ?? '' );

		// Any product option (frontend additional options, a resolved characteristic,
		// or the product's own bundled options such as delivery-code) means the label
		// carries more than the base parcel and must stay on the legacy path.
		$has_product_options = ! empty( $item_info->get_product_options() )
			|| ! empty( $item_info->shipment['product_options']['characteristic'] )
			|| ! empty( $item_info->shipment['shipping_product']['options'] );

		return array(
			'num_labels'          => (int) ( $item_info->backend_data['num_labels'] ?? 1 ),
			'is_delivery_day'     => $item_info->is_delivery_day(),
			'is_pickup'           => $item_info->is_pickup_points(),
			'has_return'          => $has_return,
			'has_product_options' => $has_product_options,
			'delivery_type'       => (string) ( $item_info->backend_data['delivery_type'] ?? 'Standard' ),
			'origin'              => $origin,
			'destination'         => $destination,
			'mapped'              => Eligibility::resolve_mapped(
				$origin,
				$destination,
				$item_info->is_pickup_points(),
				$backend_raw,
				(string) $item_info->get_product_code()
			),
		);
	}

	/**
	 * Flatten the parsed item info into the field array Request_Builder consumes.
	 *
	 * @param Shipping\Item_Info $item_info Parsed legacy item info.
	 * @param array              $mapped    V4_Mapper::map() result.
	 * @param array              $post_data Original label post data.
	 * @return array
	 */
	private function extract_fields( Shipping\Item_Info $item_info, array $mapped, array $post_data ): array {
		return array(
			'sender'        => array(
				'company'          => $item_info->shipper['company'] ?? '',
				'street'           => $item_info->shipper['address_1'] ?? '',
				'house_number'     => $item_info->shipper['address_2'] ?? '',
				'house_number_ext' => '',
				'postcode'         => $item_info->shipper['postcode'] ?? '',
				'city'             => $item_info->shipper['city'] ?? '',
				'country'          => $item_info->shipper['country'] ?? '',
			),
			'receiver'      => array(
				'company'          => $item_info->receiver['company'] ?? '',
				'first_name'       => $item_info->receiver['first_name'] ?? '',
				'last_name'        => $item_info->receiver['last_name'] ?? '',
				'street'           => $item_info->receiver['address_1'] ?? '',
				'house_number'     => $item_info->receiver['house_number'] ?? '',
				'house_number_ext' => $item_info->receiver['address_2'] ?? '',
				'postcode'         => $item_info->receiver['postcode'] ?? '',
				'city'             => $item_info->receiver['city'] ?? '',
				'country'          => $item_info->receiver['country'] ?? '',
				'email'            => $item_info->shipment['email'] ?? '',
				'phone'            => $item_info->shipment['phone'] ?? '',
			),
			'shipment_type' => $mapped['shipmentType'] ?? 'parcel',
			'weight_gr'     => (int) ( $item_info->shipment['total_weight'] ?? 0 ),
			'reference'     => (string) ( $item_info->shipment['order_number'] ?? '' ),
			'barcode'       => (string) ( $post_data['main_barcode'] ?? '' ),
			'label'         => Request_Builder::printer_type_to_label_settings(
				(string) ( $item_info->shipment['printer_type'] ?? '' )
			),
		);
	}

	/**
	 * Build the configured SDK client for the current environment.
	 *
	 * @return PostnlClientInterface
	 */
	private function build_client(): PostnlClientInterface {
		return $this->client_factory->build( $this->v4_key, (bool) $this->settings->is_sandbox() );
	}

	/**
	 * Write the labelconfirm response labels to disk and normalize them.
	 *
	 * Reuses Order\Base::maybe_merge_labels() so the A4/A6 handling matches the
	 * legacy path, then re-tags the merged record as V4.
	 *
	 * @param LabelConfirmResponseInterface $response         labelconfirm response.
	 * @param \WC_Order                     $order            WooCommerce order.
	 * @param string                        $fallback_barcode Barcode to use if the response omits one.
	 * @return array
	 * @throws \Exception When the response carries no shipment or no label content.
	 */
	private function store_labels( LabelConfirmResponseInterface $response, $order, string $fallback_barcode ): array {
		$item = Response_Mapper::first_shipment_item( $response );

		if ( null === $item ) {
			throw new \Exception(
				esc_html__( 'Cannot create the label. No shipment was returned by PostNL.', 'postnl-for-woocommerce' )
			);
		}

		$barcode = Response_Mapper::get_barcode( $item, $fallback_barcode );
		$records = array();

		foreach ( Response_Mapper::get_labels( $item ) as $label ) {
			$content = Response_Mapper::decode_content( $label );

			if ( '' === $content ) {
				continue;
			}

			// phpcs:disable WordPress.NamingConventions.ValidVariableName.UsedPropertyNotSnakeCase -- Third-party SDK DTO properties.
			$output_type = null !== $label->outputType ? $label->outputType->value : 'pdf';
			$label_type  = ( null !== $label->labelType && '' !== $label->labelType )
				? sanitize_title( $label->labelType )
				: 'label';
			// phpcs:enable WordPress.NamingConventions.ValidVariableName.UsedPropertyNotSnakeCase

			$filename = Utils::generate_label_name( $order->get_id(), $label_type, $barcode, 'A6', $output_type );
			$filepath = trailingslashit( POSTNL_UPLOADS_DIR ) . $filename;

			$this->write_label_file( $filepath, $content );

			// Only record a label that actually exists on disk, so a failed write
			// never persists a meta entry pointing at a missing file.
			if ( ! is_file( $filepath ) ) {
				continue;
			}

			$records[] = Response_Mapper::to_label_record( $label_type, $barcode, $filepath );
		}

		if ( empty( $records ) ) {
			throw new \Exception(
				esc_html__( 'Cannot create the label. Label content is missing', 'postnl-for-woocommerce' )
			);
		}

		$labels = $this->maybe_merge_labels( $records, $order, $barcode, 'label' );

		foreach ( array_keys( $labels ) as $key ) {
			$labels[ $key ]['api_version'] = 'v4';
		}

		return $labels;
	}

	/**
	 * Write a decoded label document to disk, creating the uploads dir as needed.
	 *
	 * A pre-existing file is left untouched. Failure is intentionally silent —
	 * store_labels() verifies the file exists afterwards and skips the record if
	 * it does not.
	 *
	 * @param string $filepath Absolute destination path.
	 * @param string $content  Raw (decoded) label bytes.
	 * @return void
	 */
	private function write_label_file( string $filepath, string $content ): void {
		if ( is_file( $filepath ) ) {
			return;
		}

		if ( ! wp_mkdir_p( POSTNL_UPLOADS_DIR ) ) {
			return;
		}

		// phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_file_put_contents -- Binary label bytes; mirrors Order\Base::put_label_content().
		file_put_contents( $filepath, $content );
	}
}
