<?php
/**
 * Interface Smart_Returns_Service_Interface.
 *
 * @package PostNLWooCommerce\Rest_API\Contracts
 */

namespace PostNLWooCommerce\Rest_API\Contracts;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Contract for Smart Return (printer-less return label) generation services.
 *
 * Smart Returns allow customers to return parcels without printing a label at
 * home; they receive a barcode by email and show it at a PostNL pickup point.
 * The barcode is a "PrintcodeLabel" PDF generated by the PostNL label API.
 *
 * Covers the Smart_Returns\Client (/shipment/v2_2/label/).  Called from
 * Order\Single::postnl_send_smart_return_email(), which extracts the base64 PDF
 * from the response, writes it to the uploads directory, attaches it to a
 * WC_Smart_Return_Email, and sends it to the customer's billing email address.
 *
 * Both the Legacy (V1) and any future V4 transport must implement this interface.
 * Callers in Order\Single never need to know which transport provided the label.
 */
interface Smart_Returns_Service_Interface {

	/**
	 * Generate a Smart Return barcode PDF for a WooCommerce order.
	 *
	 * Derived from Order\Single::postnl_send_smart_return_email(), which:
	 *   1. Constructs Smart_Returns\Item_Info from the \WC_Order object.
	 *      Item_Info reads billing/shipping address, store settings, and the
	 *      return-to-home flag to build the customer, message, and store sub-arrays.
	 *   2. Constructs Smart_Returns\Client with that Item_Info.
	 *   3. Calls send_request() on the client.
	 *   4. Iterates $response['ResponseShipments'][n]['Labels'] looking for
	 *      $label['Labeltype'] === 'PrintcodeLabel'.
	 *   5. Base64-decodes $label['Content'] and writes it to
	 *      wp_upload_dir()['path'] . '/printcode_label.pdf'.
	 *   6. Passes the file path to WC_Smart_Return_Email::trigger().
	 *
	 * The current PostNL endpoint is /shipment/v2_2/label/ (POST).
	 * The product code used is '3285' (return-to-home) or '2285' (freepost),
	 * controlled by Settings::is_return_to_home_enabled().
	 *
	 * @param \WC_Order $order The WooCommerce order for which to generate the
	 *                         Smart Return barcode.  Used by Smart_Returns\Item_Info
	 *                         to read billing/shipping address fields and order ID.
	 *
	 * @return array {
	 *     JSON-decoded PostNL /shipment/v2_2/label/ response body.
	 *
	 *     @type array $ResponseShipments {
	 *         Indexed array, one entry per requested shipment.
	 *         @type array $item {
	 *             @type array $Labels {
	 *                 Indexed array of label records.  The caller searches for the
	 *                 entry with Labeltype === 'PrintcodeLabel'.
	 *                 @type array $label_item {
	 *                     @type string $Labeltype 'PrintcodeLabel' for the Smart Return
	 *                                            barcode, other values for auxiliary labels.
	 *                     @type string $Content   Base64-encoded PDF content of the label.
	 *                                            Decoded and saved to disk by the caller.
	 *                 }
	 *             }
	 *         }
	 *     }
	 * }
	 *
	 * @throws \Exception If the API request fails (network error, authentication
	 *                    failure, or the response body cannot be parsed).  A response
	 *                    that does not contain a PrintcodeLabel is handled by the
	 *                    caller (Order\Single) rather than by this method.
	 */
	public function generate( \WC_Order $order ): array;
}
